{% set name = "nurikit" %}
{% set version = "0.1.0a16" %}

package:
  name: nurikit-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nurikit-{{ version }}.tar.gz
  sha256: 08bda44b8bb8b5ceebb76f1a4d70e2a78d7847df592e3545155357dc82551a44

build:
  number: 0
  skip: true  # [win]

outputs:
  - name: libnurikit

    build:
      script: |
        cmake -S. -B build ${CMAKE_ARGS} -GNinja \
          -DNURI_BUILD_PYTHON=OFF \
          -DNURI_PREBUILT_ABSL=OFF \
          -DNURI_FORCE_VERSION="${PKG_VERSION}" \
          -DBUILD_TESTING=OFF
        cmake --build build --target all -j "${CPU_COUNT}"
        cmake --build build --target install/strip

      run_exports:
        - {{ pin_subpackage("libnurikit", exact=True) }}

      ignore_run_exports_from:
        # We use headers only, but need -devel instead -headers for cmake
        - libboost-devel

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake >=3.16
        - ninja
      host:
        - libboost-devel
        - libabseil
        - eigen >=3.4
        - spectralib >=1.0
      run_constrained:
        - {{ pin_compatible("libboost-headers", max_pin="x.x") }}

    test:
      commands:
        - nuri
        - test -f "$PREFIX/lib/libnuri${SHLIB_EXT}"
        - test -f "$PREFIX/include/nuri/nurikit_config.h"
        - |
          cmake -Bbuild -S. ${CMAKE_ARGS} -GNinja \
            -DNURI_BUILD_LIB=OFF \
            -DNURI_BUILD_PYTHON=OFF \
            -DNURI_PREBUILT_ABSL=OFF \
            -DNURI_FORCE_VERSION="${PKG_VERSION}" \
            -DBUILD_TESTING=ON
          cmake --build build --target all -j "${CPU_COUNT}"

          cd build
          ctest -C Release -T test --output-on-failure -j "${CPU_COUNT}"
      source_files:
        - CMakeLists.txt
        - cmake
        - test
      requires:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake >=3.16
        - ninja
        - libboost-devel
        - libabseil
        - eigen
        - gtest

  - name: nurikit

    build:
      script: |
        export CMAKE_ARGS="${CMAKE_ARGS} -GNinja \
          -DNURI_BUILD_LIB=OFF \
          -DNURI_PREBUILT_ABSL=OFF \
          -DBUILD_TESTING=OFF"
        export CMAKE_BUILD_PARALLEL_LEVEL="${CPU_COUNT}"
        {{ PREFIX }}/bin/python -m pip install . -vv --no-deps

      ignore_run_exports_from:
        # We use headers only, but need -devel instead -headers for cmake
        - libboost-devel

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake >=3.16
        - ninja
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - pybind11                            # [build_platform != target_platform]
      host:
        - python
        - libboost-devel
        - libabseil
        - eigen >=3.4
        - pybind11 >=2.12  # For numpy 2
        - scikit-build-core >=0.10
        - pip
        - {{ pin_subpackage("libnurikit", exact=True) }}
      run:
        - python
        - numpy <3.0
        - {{ pin_subpackage("libnurikit", exact=True) }}

    test:
      imports:
        - nuri
      commands:
        - pip check
        - pytest -vs
      source_files:
        - pyproject.toml
        - python/test
        - test/test_data
      requires:
        - pip
        - pytest
        - scipy

about:
  home: https://github.com/seoklab/nurikit
  summary: "*The* fundamental software platform for chem- and bio-informatics"
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE.md
  doc_url: https://nurikit.readthedocs.io
  dev_url: https://github.com/seoklab/nurikit

extra:
  feedstock-name: nurikit
  recipe-maintainers:
    - jnooree
