{% set name = "nurikit" %}
{% set version = "0.1.0a14.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nurikit-{{ version }}.tar.gz
  sha256: af4d7702fa51671d3bbe5e17474d1116e6763b5a466b49f3be5861b83d422411

build:
  script: |
    export CMAKE_ARGS="${CMAKE_ARGS} -GNinja -DNURI_PREBUILT_ABSL=OFF -DBUILD_TESTING=OFF"
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [win]
  skip: true  # [linux and not x86_64]

  ignore_run_exports_from:
    # We use headers only, but need -devel instead -headers for cmake
    - libboost-devel

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.16
    - ninja
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - pybind11                            # [build_platform != target_platform]
  host:
    - python
    - libboost-devel >=1.82
    - libabseil >=20240116
    - eigen >=3.4
    - spectralib >=1.0
    - pybind11 >=2.12  # For numpy 2
    - scikit-build-core >=0.10
    - pip
  run:
    - python
    - numpy <3.0

test:
  imports:
    - nuri
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/seoklab/nurikit
  summary: "*The* fundamental software platform for chem- and bio-informatics"
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE.md
  doc_url: https://nurikit.readthedocs.io
  dev_url: https://github.com/seoklab/nurikit

extra:
  recipe-maintainers:
    - jnooree
